[green_agent]
agentbeats_id = "019aba63-33b5-74c3-b3fe-2251347fa60a"
image = "ghcr.io/komyo-ai/agentbeats-tutorial-debate-judge:latest"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[[participants]]
agentbeats_id = ""
name = "pro_debater"
image = ""
env = {}

[[participants]]
agentbeats_id = ""
name = "con_debater"
image = ""
env = {}

[config]
topic = "Should artificial intelligence be regulated?"
num_rounds = 2
